codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

# everything above is default (see https://docs.codecov.io/docs/codecov-yaml)
# below, we customize the codecoverage to ignore certain files we don't 
# actually use (and which otherwise just artificially reduces coverage)
# or which ported out of Crystalline.jl
ignore:
  - "src/special_representation_domain_kpoints.jl"
  - "src/export2mpb.jl"